### ISSUE TITLE
When will you release the data and code?

### ISSUE THREAD

**Issue by eugenelawrence** [weiliansong/A-Scan2BIM#1]
When will you release the data and code?

**Comment by weiliansong** [comment]
Hi Lawrence. Sorry for the delay, the data and code will be released by this coming Monday.

**Comment by weiliansong** [comment]
The repo has been updated for training/evaluation. To request data, please fill out [this form](https://forms.gle/EoNLGRRXLvcHodGc9) and we will be in contact to send the download links.
