### ISSUE TITLE
Debug issue

### ISSUE THREAD

**Issue by dtnghla** [weiliansong/A-Scan2BIM#3]
May I ask how to debug when my Revit only says Error during suggestion drawing.

**Comment by hcscysh** [comment]
Client connects to server. Can you provide detailed connection process，Thanks you!When I down loading the data, I run the data_gen.py, cropped_pcd = crop_pc(pcd, bounds),the number of poins in cropped_pcd is zero,do you meet the same problem,how you solve it ?

**Comment by dtnghla** [comment]
> Client connects to server. Can you provide detailed connection process，Thanks you!When I down loading the data, I run the data_gen.py, cropped_pcd = crop_pc(pcd, bounds),the number of poins in cropped_pcd is zero,do you meet the same problem,how you solve it ?

The plugin works fine with the provided point cloud but not my data. As for your problem, I didn't face the same issues. May be checking the input (pcd) might help?

**Comment by hcscysh** [comment]
Thanks for your reply. Can you show the next wall in the demo?  I only can obtain prediction, but can't start the autocomplete to show the next wall follwing the guide.
To enable assistance, first go to the Add-Ins tab and click on Autocomplete. The icon should change into a pause logo.
Now manually draw one wall, hit the Escape key twice to exit the "Modify Wall" mode, and you should see the next three suggested walls in solid (next) and dashed (subsequent) pink lines. Can you show the information in the plugin?

**Comment by dtnghla** [comment]
Ah, I ran into the same problem. Switching to 3D View solve this

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
